### ISSUE TITLE
[Suggestion] Option to playout customround indefinitely

### ISSUE THREAD

**Issue by mavproductions** [schwarper/cs2-customrounds#13]
Hi there!
Some of my players would enjoy to practice a certain weapon, so having a vote nag them to extend or switch is not ideal. It would be perhaps optimal to have a command like `!infiniteRounds` (maybe better wording) or in the votes, not only have an extend option, but allow people to vote play mode indefinitely until players wish to `"rockthevote"` or something of the sort.

Thanks for making this plugin! 🙂

**Comment by schwarper** [comment]
Added, you can use -i for infinite rounds. Thanks
