### ISSUE TITLE
[SUG] Add some features

### ISSUE THREAD

**Issue by rodopoulos1** [schwarper/cs2-customrounds#2]
Can u add something like hp, speed, gravity, jumps (in air), healthshot, and some antoher thing like that 
And add command to the VIP player with specific flag for the VIP can start the vote

**Comment by schwarper** [comment]
Health and Speed are already exists. You can set gravity in Cmd as "sv_gravity 200". You can give healthshot in weapons as "healthshot". And flag is added. Thanks.
