### ISSUE TITLE
Small issue

### ISSUE THREAD

**Issue by bruksgod** [schwarper/cs2-customrounds#21]
If there is a custom round going and the last 2 remaining players start a duel (SlayerDuel)  the duel gun won't appear unless the custom round has that specific gun in it.

At the same time, the rounds won't add up to the counter if there were duels in the last rounds.

**Comment by schwarper** [comment]
Added https://github.com/schwarper/cs2-customrounds/commit/f8d7fcd7c1619eadb490b552649472fac9b603a5
